In [36]:
import numpy as np
import pandas as pd

In [37]:
work_order_df = pd.read_excel(
    "F:\PyTorch_GPU\Monday_board_automation\Data\Work_Order_Tracker Data.xlsx"
)
work_order_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,Deal name masked,Customer Name Code,Serial #,Nature of Work,Last executed month of recurring project,Execution Status,Data Delivery Date,Date of PO/LOI,Document Type,Probable Start Date,...,Quantity billed (till date),Balance in quantity,Invoice Status,Expected Billing Month,Actual Billing Month,Actual Collection Month,WO Status (billed),Collection status,Collection Date,Billing Status
1,Scooby-Doo,WOCOMPANY_002,SDPLDEAL-075,One time Project,NaN,Completed,2025-09-27 00:00:00,2025-10-29 00:00:00,Purchase Order,2025-05-31 00:00:00,...,NaN,5360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Update Required
2,Appa,WOCOMPANY_038,SDPLDEAL-101,Proof of Concept,NaN,Not Started,NaN,2025-07-31 00:00:00,Purchase Order,2025-08-11 00:00:00,...,NaN,4,NaN,NaN,NaN,NaN,Open,NaN,NaN,NaN
3,Sakura,WOCOMPANY_002,SDPLDEAL-002,Monthly Contract,Dec,Executed until current month,2025-12-31 00:00:00,2025-05-16 00:00:00,Purchase Order,2025-05-01 00:00:00,...,NaN,3000,NaN,NaN,NaN,NaN,Open,NaN,NaN,Partially Billed
4,Sakura,WOCOMPANY_002,SDPLDEAL-003,One time Project,NaN,Completed,NaN,2025-05-08 00:00:00,Purchase Order,2025-05-20 00:00:00,...,NaN,600,Not billed yet,NaN,NaN,NaN,Open,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Bulbasaur,WOCOMPANY_050,SDPLDEAL-185,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Email Confirmation,2026-01-12 00:00:00,...,NaN,7000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,Timon,WOCOMPANY_046,SDPLDEAL-186,One time Project,NaN,Ongoing,NaN,2026-01-06 00:00:00,Purchase Order,2026-01-13 00:00:00,...,NaN,1,Not billed yet,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Ben Tennyson,WOCOMPANY_033,SDPLDEAL-187,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-19 00:00:00,...,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,Ben Tennyson,WOCOMPANY_033,SDPLDEAL-188,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-19 00:00:00,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,NaN,WOCOMPANY_045,SDPLDEAL-189,Proof of Concept,NaN,Ongoing,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-17 00:00:00,...,NaN,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
work_order_df.describe()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
count,176,177,177,165,16,173,59,176,163,159,...,24,158,113,1,71,1,103,1,1,29
unique,59,52,177,5,6,8,43,104,4,88,...,18,96,7,1,8,1,3,1,1,6
top,Alias_160,WOCOMPANY_051,Serial #,One time Project,Dec,Completed,2025-05-13 00:00:00,2025-04-10 00:00:00,Purchase Order,2025-05-01 00:00:00,...,1,1,Fully Billed,Expected Billing Month,July,Actual Collection Month,Closed,Collection status,Collection Date,Update Required
freq,21,26,1,125,6,117,3,44,141,25,...,7,32,91,1,24,1,78,1,1,12

In [39]:
work_order_df.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37'],
      dtype='object')

### Using the First Row as Column Names

The first row of the Excel data contains the actual column names. To set these as the DataFrame's column headers, we re-read the file with `header=0` or reset the columns using the first row.

In [40]:
# Set the first row as column names
work_order_df.columns = work_order_df.iloc[0]
work_order_df = work_order_df[1:].reset_index(drop=True)
work_order_df.head()

,Deal name masked,Customer Name Code,Serial #,Nature of Work,Last executed month of recurring project,Execution Status,Data Delivery Date,Date of PO/LOI,Document Type,Probable Start Date,...,Quantity billed (till date),Balance in quantity,Invoice Status,Expected Billing Month,Actual Billing Month,Actual Collection Month,WO Status (billed),Collection status,Collection Date,Billing Status
0,Scooby-Doo,WOCOMPANY_002,SDPLDEAL-075,One time Project,NaN,Completed,2025-09-27 00:00:00,2025-10-29 00:00:00,Purchase Order,2025-05-31 00:00:00,...,NaN,5360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Update Required
1,Appa,WOCOMPANY_038,SDPLDEAL-101,Proof of Concept,NaN,Not Started,NaN,2025-07-31 00:00:00,Purchase Order,2025-08-11 00:00:00,...,NaN,4,NaN,NaN,NaN,NaN,Open,NaN,NaN,NaN
2,Sakura,WOCOMPANY_002,SDPLDEAL-002,Monthly Contract,Dec,Executed until current month,2025-12-31 00:00:00,2025-05-16 00:00:00,Purchase Order,2025-05-01 00:00:00,...,NaN,3000,NaN,NaN,NaN,NaN,Open,NaN,NaN,Partially Billed
3,Sakura,WOCOMPANY_002,SDPLDEAL-003,One time Project,NaN,Completed,NaN,2025-05-08 00:00:00,Purchase Order,2025-05-20 00:00:00,...,NaN,600,Not billed yet,NaN,NaN,NaN,Open,NaN,NaN,NaN
4,SpongeBob,WOCOMPANY_032,SDPLDEAL-004,One time Project,NaN,Completed,NaN,2025-05-06 00:00:00,LOA/LOI,2025-05-24 00:00:00,...,NaN,59.33,NaN,NaN,NaN,NaN,Open,NaN,NaN,BIlled

In [41]:
work_order_df

,Deal name masked,Customer Name Code,Serial #,Nature of Work,Last executed month of recurring project,Execution Status,Data Delivery Date,Date of PO/LOI,Document Type,Probable Start Date,...,Quantity billed (till date),Balance in quantity,Invoice Status,Expected Billing Month,Actual Billing Month,Actual Collection Month,WO Status (billed),Collection status,Collection Date,Billing Status
0,Scooby-Doo,WOCOMPANY_002,SDPLDEAL-075,One time Project,NaN,Completed,2025-09-27 00:00:00,2025-10-29 00:00:00,Purchase Order,2025-05-31 00:00:00,...,NaN,5360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Update Required
1,Appa,WOCOMPANY_038,SDPLDEAL-101,Proof of Concept,NaN,Not Started,NaN,2025-07-31 00:00:00,Purchase Order,2025-08-11 00:00:00,...,NaN,4,NaN,NaN,NaN,NaN,Open,NaN,NaN,NaN
2,Sakura,WOCOMPANY_002,SDPLDEAL-002,Monthly Contract,Dec,Executed until current month,2025-12-31 00:00:00,2025-05-16 00:00:00,Purchase Order,2025-05-01 00:00:00,...,NaN,3000,NaN,NaN,NaN,NaN,Open,NaN,NaN,Partially Billed
3,Sakura,WOCOMPANY_002,SDPLDEAL-003,One time Project,NaN,Completed,NaN,2025-05-08 00:00:00,Purchase Order,2025-05-20 00:00:00,...,NaN,600,Not billed yet,NaN,NaN,NaN,Open,NaN,NaN,NaN
4,SpongeBob,WOCOMPANY_032,SDPLDEAL-004,One time Project,NaN,Completed,NaN,2025-05-06 00:00:00,LOA/LOI,2025-05-24 00:00:00,...,NaN,59.33,NaN,NaN,NaN,NaN,Open,NaN,NaN,BIlled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,Bulbasaur,WOCOMPANY_050,SDPLDEAL-185,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Email Confirmation,2026-01-12 00:00:00,...,NaN,7000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,Timon,WOCOMPANY_046,SDPLDEAL-186,One time Project,NaN,Ongoing,NaN,2026-01-06 00:00:00,Purchase Order,2026-01-13 00:00:00,...,NaN,1,Not billed yet,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173,Ben Tennyson,WOCOMPANY_033,SDPLDEAL-187,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-19 00:00:00,...,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Ben Tennyson,WOCOMPANY_033,SDPLDEAL-188,One time Project,NaN,Not Started,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-19 00:00:00,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,NaN,WOCOMPANY_045,SDPLDEAL-189,Proof of Concept,NaN,Ongoing,NaN,2026-01-09 00:00:00,Purchase Order,2026-01-17 00:00:00,...,NaN,30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
work_order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 38 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   Deal name masked                                                                175 non-null    object
 1   Customer Name Code                                                              176 non-null    object
 2   Serial #                                                                        176 non-null    object
 3   Nature of Work                                                                  164 non-null    object
 4   Last executed month of recurring project                                        15 non-null     object
 5   Execution Status                                                                172 non-null    object
 6   Data Delivery Date                                                              58 non-null     object
 7   Date of PO/LOI                                                                  175 non-null    object
 8   Document Type                                                                   162 non-null    object
 9   Probable Start Date                                                             158 non-null    object
 10  Probable End Date                                                               157 non-null    object
 11  BD/KAM Personnel code                                                           165 non-null    object
 12  Sector                                                                          176 non-null    object
 13  Type of Work                                                                    176 non-null    object
 14  Is any Skylark software platform part of the client deliverables in this deal?  164 non-null    object
 15  Last invoice date                                                               87 non-null     object
 16  latest invoice no.                                                              88 non-null     object
 17  Amount in Rupees (Excl of GST) (Masked)                                         175 non-null    object
 18  Amount in Rupees (Incl of GST) (Masked)                                         176 non-null    object
 19  Billed Value in Rupees (Excl of GST.) (Masked)                                  113 non-null    object
 20  Billed Value in Rupees (Incl of GST.) (Masked)                                  176 non-null    object
 21  Collected Amount in Rupees (Incl of GST.) (Masked)                              78 non-null     object
 22  Amount to be billed in Rs. (Exl. of GST) (Masked)                               176 non-null    object
 23  Amount to be billed in Rs. (Incl. of GST) (Masked)                              176 non-null    object
 24  Amount Receivable (Masked)                                                      176 non-null    object
 25  AR Priority account                                                             10 non-null     object
 26  Quantity by Ops                                                                 43 non-null     object
 27  Quantities as per PO                                                            160 non-null    object
 28  Quantity billed (till date)                                                     23 non-null     object
 29  Balance in quantity                                                             157 non-null    object
 30  Invoice Status                                                                  112 non-null    object
 31  Expected Billing Month                                                          0 non-null      object
 32  Actual Billing Month                                                            70 non-null     object
 33  Actual Collection Month                                                         0 non-null      object
 34  WO Status (billed)                                                              102 non-null    object
 35  Collection status                                                               0 non-null      object
 36  Collection Date                                                                 0 non-null      object
 37  Billing Status                                                                  28 non-null     object
dtypes: object(38)
memory usage: 52.4+ KB